# generated by 'xml2py'
# flags '-v -c -kdefst -l nicaiu -o gary.py gary.xml'
from ctypes import *

_libraries = {}
_libraries['nicaiu'] = CDLL('nicaiu')


ABC = 1 # Variable c_int
DEF = 2 # Variable c_int
# gary.h 8
DAQmxStartTask = _libraries['nicaiu'].DAQmxStartTask
DAQmxStartTask.restype = c_int
# DAQmxStartTask(handle)
DAQmxStartTask.argtypes = [c_int]
__all__ = ['DAQmxStartTask', 'ABC', 'DEF']
